version: '3.8'

services:
  mongo:
    networks:
      - api_sample
    container_name: api_sample_mongodb
    image: mongo
    env_file:
      - .env
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
  api:
    depends_on:
      - mongo
    networks:
      - api_sample
    container_name: api_sample
    build:
      context: .
    image: api
    env_file:
      - .env
    restart: always
    volumes:
      - ./:/code
      - ./node_modules:/code/node_modules
    ports:
      - ${APPLICATION_PORT}:3000
networks:
  api_sample:
    driver: bridge
